#!/bin/sh -e
# bamboo startup script
#chkconfig: 2345 80 05
#description: bamboo

# Define some variables
# Name of app ( bamboo, Confluence, etc )
APP=bamboo
# Name of the user to run as
USER=bamboo
# Location of application's bin directory
BASE=$BAMBOO_APP_HOME
# Location of Java JDK
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
export HOME=/home/bamboo

case "$1" in
  # Start command
  start)
    echo "Starting $APP"
    /bin/su -m $USER -c "cd $BASE/logs && $BASE/atlassian-bamboo-5.15.7/bin/startup.sh &> /dev/null"
    ;;
  # Stop command
  stop)
    echo "Stopping $APP"
    /bin/su -m $USER -c "$BASE/atlassian-bamboo-5.15.7/bin/shutdown.sh &> /dev/null"
    echo "$APP stopped successfully"
    ;;
   # Restart command
   restart)
        $0 stop
        sleep 5
        $0 start
        ;;
  *)
    echo "Usage: /etc/init.d/$APP {start|restart|stop}"
    exit 1
    ;;
esac
